version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    networks:
    - docker-django
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
       - django:/var/lib/postgresql/data
    networks:
      - docker-django
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
    networks:
      - docker-django
networks:
  docker-django:
    driver: bridge
volumes:
  django: